version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: "mongodb://mongo:27017/test"
    depends_on:
      - mongo
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    command: npx nodemon -L app.js

  mongo:
    image: mongo:latest
    platform: linux/amd64
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
